#!/usr/bin/env bash
# Regenerate db/schema.sql: every migration's up section applied to an empty database, then
# pg_dump --schema-only, both run INSIDE the pinned ParadeDB container so the dump's client version
# always matches the server (schema card). Deterministic: volatile header lines are stripped.
#
# usage: db/dump-schema.sh [--check]     --check exits 1 if db/schema.sql is stale (for CI)
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

COMPOSE=(docker compose -p wf-schema -f infra/spikes/s3/compose.yml)
DB="wf_schema_dump_$$"
psql_c() { "${COMPOSE[@]}" exec -T paradedb psql -v ON_ERROR_STOP=1 -q -U wayfinder "$@"; }

"${COMPOSE[@]}" up -d --wait >/dev/null
# template0, not the image's template1: template1 pre-installs postgis and friends, which are not
# ours and would otherwise appear in the snapshot.
psql_c -d s3spike -c "CREATE DATABASE \"$DB\" TEMPLATE template0"
trap 'psql_c -d s3spike -c "DROP DATABASE IF EXISTS \"$DB\" WITH (FORCE)" >/dev/null' EXIT

for m in db/migrations/*.sql; do
  awk '/^-- migrate:up/{on=1; next} /^-- migrate:down/{on=0} on' "$m" | psql_c -d "$DB"
done

out="$("${COMPOSE[@]}" exec -T paradedb pg_dump -U wayfinder --schema-only --no-owner --no-privileges "$DB" \
  | grep -v -E '^(\\restrict|\\unrestrict|-- Dumped (from|by) )')"
header="-- Generated by db/dump-schema.sh from db/migrations/*.sql. Do not edit; regenerate."

if [[ "${1:-}" == "--check" ]]; then
  diff -u db/schema.sql <(printf '%s\n%s\n' "$header" "$out") >/dev/null \
    || { echo "::error::db/schema.sql is stale; run db/dump-schema.sh and commit it" >&2; exit 1; }
  echo "db/schema.sql is current"
else
  printf '%s\n%s\n' "$header" "$out" > db/schema.sql
  echo "wrote db/schema.sql ($(wc -l < db/schema.sql) lines)"
fi
