-- Generated by db/dump-schema.sh from db/migrations/*.sql. Do not edit; regenerate.
--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: paradedb; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA paradedb;


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


--
-- Name: pg_search; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_search WITH SCHEMA paradedb;


--
-- Name: EXTENSION pg_search; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_search IS 'pg_search: Full text search for PostgreSQL using BM25';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: answer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.answer (
    id uuid NOT NULL,
    principal_id bigint NOT NULL,
    status text NOT NULL,
    mode text NOT NULL,
    query text NOT NULL,
    canonical_text text,
    citations jsonb,
    evidence_manifest jsonb NOT NULL,
    classification text NOT NULL,
    pipeline_config text NOT NULL,
    degraded text[] DEFAULT '{}'::text[] NOT NULL,
    provider text,
    model text,
    usage jsonb,
    terminal_reason text,
    cached_from uuid,
    idempotency_key bytea,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT answer_mode_check CHECK ((mode = ANY (ARRAY['locate'::text, 'generated'::text, 'refused'::text, 'extractive'::text]))),
    CONSTRAINT answer_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'streaming'::text, 'completed'::text, 'refused'::text, 'extractive'::text, 'failed'::text, 'cancelled'::text])))
);


--
-- Name: answer_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.answer_cache (
    cache_key bytea NOT NULL,
    answer_id uuid NOT NULL,
    expires_at timestamp with time zone NOT NULL
);


--
-- Name: answer_trace; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.answer_trace (
    answer_id uuid NOT NULL,
    trace jsonb NOT NULL
);


--
-- Name: audit_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_event (
    id bigint NOT NULL,
    kind text NOT NULL,
    subject text,
    detail jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: audit_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.audit_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: audit_event_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.audit_event_id_seq OWNED BY public.audit_event.id;


--
-- Name: connection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.connection (
    id bigint NOT NULL,
    mode text NOT NULL,
    github_installation_id bigint,
    account_login text NOT NULL,
    state text NOT NULL,
    state_observed_at timestamp with time zone NOT NULL,
    state_valid_until timestamp with time zone NOT NULL,
    egress_policy jsonb NOT NULL,
    policy_revision bigint DEFAULT 1 NOT NULL,
    config jsonb NOT NULL,
    CONSTRAINT connection_mode_check CHECK ((mode = ANY (ARRAY['installation'::text, 'public_readonly'::text]))),
    CONSTRAINT connection_state_check CHECK ((state = ANY (ARRAY['active'::text, 'suspended'::text, 'deleted'::text])))
);


--
-- Name: connection_admin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.connection_admin (
    connection_id bigint NOT NULL,
    principal_id bigint NOT NULL
);


--
-- Name: connection_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.connection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: connection_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.connection_id_seq OWNED BY public.connection.id;


--
-- Name: content; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content (
    content_hash bytea NOT NULL,
    body text NOT NULL,
    language text,
    token_count integer NOT NULL
);


--
-- Name: repository; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.repository (
    id bigint NOT NULL,
    connection_id bigint NOT NULL,
    github_repo_id bigint NOT NULL,
    full_name text NOT NULL,
    default_branch text NOT NULL,
    visibility text NOT NULL,
    visibility_observed_at timestamp with time zone NOT NULL,
    visibility_valid_until timestamp with time zone NOT NULL,
    serving_state text NOT NULL,
    data_class text NOT NULL,
    authorization_revision bigint DEFAULT 1 NOT NULL,
    desired_generation bigint DEFAULT 0 NOT NULL,
    claim_token uuid,
    claim_expires_at timestamp with time zone,
    active_generation_id bigint,
    license_spdx text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT repository_data_class_check CHECK ((data_class = ANY (ARRAY['public'::text, 'private'::text]))),
    CONSTRAINT repository_serving_state_check CHECK ((serving_state = ANY (ARRAY['active'::text, 'denied'::text, 'removed'::text]))),
    CONSTRAINT repository_visibility_check CHECK ((visibility = ANY (ARRAY['public'::text, 'private'::text, 'internal'::text])))
);


--
-- Name: eligible_repo; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.eligible_repo AS
 SELECT r.id AS repo_id,
    r.data_class,
    ((r.visibility = 'public'::text) AND (r.visibility_valid_until > now())) AS verified_public
   FROM (public.repository r
     JOIN public.connection c ON ((c.id = r.connection_id)))
  WHERE ((r.serving_state = 'active'::text) AND (c.state = 'active'::text) AND (c.state_valid_until > now()) AND (r.visibility_valid_until > now()));


--
-- Name: embedding_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.embedding_cache (
    input_hash bytea NOT NULL,
    spec_id bigint NOT NULL,
    embedding public.halfvec NOT NULL,
    data_class text NOT NULL,
    CONSTRAINT embedding_cache_data_class_check CHECK ((data_class = ANY (ARRAY['public'::text, 'private'::text])))
);


--
-- Name: embedding_spec; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.embedding_spec (
    id bigint NOT NULL,
    model_ref text NOT NULL,
    model_digest text NOT NULL,
    runtime text NOT NULL,
    doc_template text NOT NULL,
    query_template text NOT NULL,
    pooling text NOT NULL,
    "normalize" boolean NOT NULL,
    dimension integer NOT NULL,
    truncation text NOT NULL,
    tokenizer_ref text NOT NULL
);


--
-- Name: embedding_spec_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.embedding_spec_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: embedding_spec_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.embedding_spec_id_seq OWNED BY public.embedding_spec.id;


--
-- Name: feedback; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feedback (
    answer_id uuid,
    principal_id bigint NOT NULL,
    rating smallint,
    reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: generation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generation (
    id bigint NOT NULL,
    repo_id bigint NOT NULL,
    desired_generation bigint NOT NULL,
    commit_sha text NOT NULL,
    spec_id bigint NOT NULL,
    chunker_version text NOT NULL,
    status text NOT NULL,
    lease_token uuid,
    heartbeat_at timestamp with time zone,
    base_generation_id bigint,
    chunk_count integer,
    skipped_manifest jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    activated_at timestamp with time zone,
    CONSTRAINT generation_status_check CHECK ((status = ANY (ARRAY['building'::text, 'ready'::text, 'active'::text, 'retired'::text, 'failed'::text])))
);


--
-- Name: generation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.generation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: generation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.generation_id_seq OWNED BY public.generation.id;


--
-- Name: occurrence; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.occurrence (
    repo_id bigint NOT NULL,
    generation_id bigint NOT NULL,
    representation_id bigint NOT NULL,
    path text NOT NULL,
    blob_sha text NOT NULL,
    start_line integer NOT NULL,
    end_line integer NOT NULL,
    symbol text
);


--
-- Name: principal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.principal (
    id bigint NOT NULL,
    kind text NOT NULL,
    github_user_id bigint,
    login text,
    token_ciphertext bytea,
    token_expires_at timestamp with time zone,
    refresh_ciphertext bytea,
    refresh_expires_at timestamp with time zone,
    platform_role text DEFAULT 'user'::text NOT NULL,
    CONSTRAINT principal_kind_check CHECK ((kind = ANY (ARRAY['user'::text, 'anonymous'::text]))),
    CONSTRAINT principal_platform_role_check CHECK ((platform_role = ANY (ARRAY['user'::text, 'operator'::text])))
);


--
-- Name: principal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.principal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: principal_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.principal_id_seq OWNED BY public.principal.id;


--
-- Name: repository_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.repository_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: repository_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.repository_id_seq OWNED BY public.repository.id;


--
-- Name: representation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.representation (
    id bigint NOT NULL,
    repo_id bigint NOT NULL,
    spec_id bigint NOT NULL,
    input_hash bytea NOT NULL,
    content_hash bytea NOT NULL,
    header text NOT NULL,
    body_text text NOT NULL,
    live boolean DEFAULT false NOT NULL
)
WITH (autovacuum_vacuum_scale_factor='0.02');


--
-- Name: representation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.representation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: representation_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.representation_id_seq OWNED BY public.representation.id;


--
-- Name: retrieval_rows; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.retrieval_rows AS
 SELECT rep.id AS representation_id,
    rep.repo_id,
    rep.spec_id,
    rep.header,
    rep.body_text,
    o.path,
    o.blob_sha,
    o.start_line,
    o.end_line,
    o.symbol,
    rep.content_hash,
    rep.live
   FROM ((public.representation rep
     JOIN public.repository r ON ((r.id = rep.repo_id)))
     JOIN public.occurrence o ON (((o.representation_id = rep.id) AND (o.repo_id = rep.repo_id) AND (o.generation_id = r.active_generation_id))))
  WHERE rep.live;


--
-- Name: session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session (
    id_hash bytea NOT NULL,
    principal_id bigint NOT NULL,
    revoked_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL
);


--
-- Name: tombstone; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tombstone (
    id bigint NOT NULL,
    scope text NOT NULL,
    ref text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT tombstone_check CHECK ((expires_at >= (created_at + '90 days'::interval))),
    CONSTRAINT tombstone_scope_check CHECK ((scope = ANY (ARRAY['repository'::text, 'representation'::text, 'connection'::text])))
);


--
-- Name: tombstone_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.tombstone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: tombstone_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.tombstone_id_seq OWNED BY public.tombstone.id;


--
-- Name: user_access_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_access_state (
    principal_id bigint NOT NULL,
    authorization_revision bigint DEFAULT 1 NOT NULL,
    refreshed_at timestamp with time zone NOT NULL,
    valid_until timestamp with time zone NOT NULL
);


--
-- Name: user_repo_access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_repo_access (
    principal_id bigint NOT NULL,
    repo_id bigint NOT NULL
);


--
-- Name: vector_d768; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vector_d768 (
    representation_id bigint NOT NULL,
    repo_id bigint NOT NULL,
    spec_id bigint NOT NULL,
    live boolean DEFAULT false NOT NULL,
    embedding public.halfvec(768) NOT NULL
);


--
-- Name: webhook_delivery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.webhook_delivery (
    delivery_id uuid NOT NULL,
    received_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: audit_event id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_event ALTER COLUMN id SET DEFAULT nextval('public.audit_event_id_seq'::regclass);


--
-- Name: connection id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.connection ALTER COLUMN id SET DEFAULT nextval('public.connection_id_seq'::regclass);


--
-- Name: embedding_spec id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embedding_spec ALTER COLUMN id SET DEFAULT nextval('public.embedding_spec_id_seq'::regclass);


--
-- Name: generation id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation ALTER COLUMN id SET DEFAULT nextval('public.generation_id_seq'::regclass);


--
-- Name: principal id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.principal ALTER COLUMN id SET DEFAULT nextval('public.principal_id_seq'::regclass);


--
-- Name: repository id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repository ALTER COLUMN id SET DEFAULT nextval('public.repository_id_seq'::regclass);


--
-- Name: representation id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.representation ALTER COLUMN id SET DEFAULT nextval('public.representation_id_seq'::regclass);


--
-- Name: tombstone id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tombstone ALTER COLUMN id SET DEFAULT nextval('public.tombstone_id_seq'::regclass);


--
-- Name: answer_cache answer_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_cache
    ADD CONSTRAINT answer_cache_pkey PRIMARY KEY (cache_key);


--
-- Name: answer answer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_pkey PRIMARY KEY (id);


--
-- Name: answer answer_principal_id_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_principal_id_idempotency_key_key UNIQUE (principal_id, idempotency_key);


--
-- Name: answer_trace answer_trace_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_trace
    ADD CONSTRAINT answer_trace_pkey PRIMARY KEY (answer_id);


--
-- Name: audit_event audit_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_event
    ADD CONSTRAINT audit_event_pkey PRIMARY KEY (id);


--
-- Name: connection_admin connection_admin_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.connection_admin
    ADD CONSTRAINT connection_admin_pkey PRIMARY KEY (connection_id, principal_id);


--
-- Name: connection connection_github_installation_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.connection
    ADD CONSTRAINT connection_github_installation_id_key UNIQUE (github_installation_id);


--
-- Name: connection connection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.connection
    ADD CONSTRAINT connection_pkey PRIMARY KEY (id);


--
-- Name: content content_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content
    ADD CONSTRAINT content_pkey PRIMARY KEY (content_hash);


--
-- Name: embedding_cache embedding_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embedding_cache
    ADD CONSTRAINT embedding_cache_pkey PRIMARY KEY (input_hash, spec_id);


--
-- Name: embedding_spec embedding_spec_model_digest_runtime_doc_template_query_temp_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embedding_spec
    ADD CONSTRAINT embedding_spec_model_digest_runtime_doc_template_query_temp_key UNIQUE (model_digest, runtime, doc_template, query_template, pooling, "normalize", dimension, truncation);


--
-- Name: embedding_spec embedding_spec_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embedding_spec
    ADD CONSTRAINT embedding_spec_pkey PRIMARY KEY (id);


--
-- Name: generation generation_id_repo_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation
    ADD CONSTRAINT generation_id_repo_id_key UNIQUE (id, repo_id);


--
-- Name: generation generation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation
    ADD CONSTRAINT generation_pkey PRIMARY KEY (id);


--
-- Name: generation generation_repo_id_commit_sha_chunker_version_spec_id_desir_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation
    ADD CONSTRAINT generation_repo_id_commit_sha_chunker_version_spec_id_desir_key UNIQUE (repo_id, commit_sha, chunker_version, spec_id, desired_generation);


--
-- Name: occurrence occurrence_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_pkey PRIMARY KEY (generation_id, representation_id, path, start_line);


--
-- Name: principal principal_github_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.principal
    ADD CONSTRAINT principal_github_user_id_key UNIQUE (github_user_id);


--
-- Name: principal principal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.principal
    ADD CONSTRAINT principal_pkey PRIMARY KEY (id);


--
-- Name: repository repository_github_repo_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repository
    ADD CONSTRAINT repository_github_repo_id_key UNIQUE (github_repo_id);


--
-- Name: repository repository_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repository
    ADD CONSTRAINT repository_pkey PRIMARY KEY (id);


--
-- Name: representation representation_id_repo_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.representation
    ADD CONSTRAINT representation_id_repo_id_key UNIQUE (id, repo_id);


--
-- Name: representation representation_id_repo_id_spec_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.representation
    ADD CONSTRAINT representation_id_repo_id_spec_id_key UNIQUE (id, repo_id, spec_id);


--
-- Name: representation representation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.representation
    ADD CONSTRAINT representation_pkey PRIMARY KEY (id);


--
-- Name: representation representation_repo_id_spec_id_input_hash_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.representation
    ADD CONSTRAINT representation_repo_id_spec_id_input_hash_key UNIQUE (repo_id, spec_id, input_hash);


--
-- Name: session session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id_hash);


--
-- Name: tombstone tombstone_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tombstone
    ADD CONSTRAINT tombstone_pkey PRIMARY KEY (id);


--
-- Name: user_access_state user_access_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_access_state
    ADD CONSTRAINT user_access_state_pkey PRIMARY KEY (principal_id);


--
-- Name: user_repo_access user_repo_access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_repo_access
    ADD CONSTRAINT user_repo_access_pkey PRIMARY KEY (principal_id, repo_id);


--
-- Name: vector_d768 vector_d768_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vector_d768
    ADD CONSTRAINT vector_d768_pkey PRIMARY KEY (representation_id);


--
-- Name: webhook_delivery webhook_delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.webhook_delivery
    ADD CONSTRAINT webhook_delivery_pkey PRIMARY KEY (delivery_id);


--
-- Name: one_active_per_repo; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX one_active_per_repo ON public.generation USING btree (repo_id) WHERE (status = 'active'::text);


--
-- Name: rep_bm25; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rep_bm25 ON public.representation USING bm25 (id, header, body_text, repo_id, live) WITH (key_field=id);


--
-- Name: rep_repo_live; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rep_repo_live ON public.representation USING btree (repo_id) WHERE live;


--
-- Name: vec768_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vec768_hnsw ON public.vector_d768 USING hnsw (embedding public.halfvec_cosine_ops) WHERE live;


--
-- Name: vec768_repo; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vec768_repo ON public.vector_d768 USING btree (repo_id, spec_id) WHERE live;


--
-- Name: answer_cache answer_cache_answer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_cache
    ADD CONSTRAINT answer_cache_answer_id_fkey FOREIGN KEY (answer_id) REFERENCES public.answer(id);


--
-- Name: answer answer_cached_from_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_cached_from_fkey FOREIGN KEY (cached_from) REFERENCES public.answer(id) ON DELETE SET NULL;


--
-- Name: answer answer_principal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer
    ADD CONSTRAINT answer_principal_id_fkey FOREIGN KEY (principal_id) REFERENCES public.principal(id);


--
-- Name: answer_trace answer_trace_answer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.answer_trace
    ADD CONSTRAINT answer_trace_answer_id_fkey FOREIGN KEY (answer_id) REFERENCES public.answer(id) ON DELETE CASCADE;


--
-- Name: connection_admin connection_admin_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.connection_admin
    ADD CONSTRAINT connection_admin_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES public.connection(id);


--
-- Name: connection_admin connection_admin_principal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.connection_admin
    ADD CONSTRAINT connection_admin_principal_id_fkey FOREIGN KEY (principal_id) REFERENCES public.principal(id);


--
-- Name: embedding_cache embedding_cache_spec_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.embedding_cache
    ADD CONSTRAINT embedding_cache_spec_id_fkey FOREIGN KEY (spec_id) REFERENCES public.embedding_spec(id);


--
-- Name: feedback feedback_answer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_answer_id_fkey FOREIGN KEY (answer_id) REFERENCES public.answer(id) ON DELETE CASCADE;


--
-- Name: feedback feedback_principal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feedback
    ADD CONSTRAINT feedback_principal_id_fkey FOREIGN KEY (principal_id) REFERENCES public.principal(id);


--
-- Name: generation generation_base_generation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation
    ADD CONSTRAINT generation_base_generation_id_fkey FOREIGN KEY (base_generation_id) REFERENCES public.generation(id) ON DELETE SET NULL;


--
-- Name: generation generation_repo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation
    ADD CONSTRAINT generation_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES public.repository(id);


--
-- Name: generation generation_spec_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generation
    ADD CONSTRAINT generation_spec_id_fkey FOREIGN KEY (spec_id) REFERENCES public.embedding_spec(id);


--
-- Name: occurrence occurrence_generation_id_repo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_generation_id_repo_id_fkey FOREIGN KEY (generation_id, repo_id) REFERENCES public.generation(id, repo_id) ON DELETE RESTRICT;


--
-- Name: occurrence occurrence_repo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES public.repository(id);


--
-- Name: occurrence occurrence_representation_id_repo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.occurrence
    ADD CONSTRAINT occurrence_representation_id_repo_id_fkey FOREIGN KEY (representation_id, repo_id) REFERENCES public.representation(id, repo_id) ON DELETE RESTRICT;


--
-- Name: repository repository_active_generation_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repository
    ADD CONSTRAINT repository_active_generation_fk FOREIGN KEY (active_generation_id, id) REFERENCES public.generation(id, repo_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: repository repository_connection_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.repository
    ADD CONSTRAINT repository_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES public.connection(id);


--
-- Name: representation representation_content_hash_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.representation
    ADD CONSTRAINT representation_content_hash_fkey FOREIGN KEY (content_hash) REFERENCES public.content(content_hash);


--
-- Name: representation representation_repo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.representation
    ADD CONSTRAINT representation_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES public.repository(id);


--
-- Name: representation representation_spec_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.representation
    ADD CONSTRAINT representation_spec_id_fkey FOREIGN KEY (spec_id) REFERENCES public.embedding_spec(id);


--
-- Name: session session_principal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session
    ADD CONSTRAINT session_principal_id_fkey FOREIGN KEY (principal_id) REFERENCES public.principal(id);


--
-- Name: user_access_state user_access_state_principal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_access_state
    ADD CONSTRAINT user_access_state_principal_id_fkey FOREIGN KEY (principal_id) REFERENCES public.principal(id);


--
-- Name: user_repo_access user_repo_access_principal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_repo_access
    ADD CONSTRAINT user_repo_access_principal_id_fkey FOREIGN KEY (principal_id) REFERENCES public.principal(id);


--
-- Name: user_repo_access user_repo_access_repo_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_repo_access
    ADD CONSTRAINT user_repo_access_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES public.repository(id);


--
-- Name: vector_d768 vector_d768_representation_id_repo_id_spec_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vector_d768
    ADD CONSTRAINT vector_d768_representation_id_repo_id_spec_id_fkey FOREIGN KEY (representation_id, repo_id, spec_id) REFERENCES public.representation(id, repo_id, spec_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--
