#!/usr/bin/env python3
"""Generate .github/CODEOWNERS from docs/team/ROSTER.md and docs/team/OWNERSHIP.md.

CODEOWNERS answers one question — *whose approval does this path need* — which is not the same as
"who implements it". GitHub never requests review from the author, so listing an implementer as the
owner of the path they write leaves that path with no required reviewer at all. Therefore:

    required reviewers for a path = the roster's reviewers
                                  + any implementer who does NOT own that path

Implementation ownership lives in docs/team/OWNERSHIP.md and is enforced by scripts/check_ownership.py.
Here it only appears as a comment, so the file stays readable.

usage: scripts/gen_codeowners.py [--check]
       --check fails if the generated file differs from the one on disk (used in CI)
"""
from __future__ import annotations
import pathlib, re, sys

OWN = pathlib.Path("docs/team/OWNERSHIP.md")
ROSTER = pathlib.Path("docs/team/ROSTER.md")
OUT = pathlib.Path(".github/CODEOWNERS")


def roster() -> tuple[dict[str, str], dict[str, str]]:
    """Returns (handle -> @github, handle -> role)."""
    block = re.search(r"```yaml\n(.*?)```", ROSTER.read_text(), re.S).group(1)
    handles: dict[str, str] = {}
    roles: dict[str, str] = {}
    current = None
    for line in block.splitlines():
        m = re.match(r"\s*-\s*handle:\s*(\S+)", line)
        if m:
            current = m.group(1)
            continue
        m = re.match(r"\s*github:\s*(\S+)", line)
        if m and current:
            handles[current] = "@" + m.group(1)
        m = re.match(r"\s*role:\s*(\S+)", line)
        if m and current:
            roles[current] = m.group(1)
    return handles, roles


def main() -> int:
    gh, roles = roster()
    reviewers = [h for h, r in roles.items() if r == "reviewer"]
    implementers = [h for h, r in roles.items() if r == "implementer"]
    base = " ".join(gh[h] for h in sorted(reviewers)) or " ".join(sorted(gh.values()))

    block = re.search(r"```yaml\n(.*?)```", OWN.read_text(), re.S).group(1)
    modules = re.findall(
        r"^\s{2}([a-z0-9-]+):\s*\{owner:\s*([^,]+),\s*paths:\s*\[(.*?)\]\}", block, re.M
    )

    lines = [
        "# Generated by scripts/gen_codeowners.py — do not hand-edit.",
        "# Source: docs/team/ROSTER.md (roles) + docs/team/OWNERSHIP.md (modules).",
        "#",
        "# These are REQUIRED REVIEWERS, not implementers: GitHub never asks the author to review their",
        "# own pull request, so an implementer listed here would leave their own paths ungated.",
        "# Implementation ownership is enforced separately by scripts/check_ownership.py.",
        "",
        f"*                                   {base}",
        "",
        "# Per-module required reviewers. Today one person implements everything, so every path needs",
        "# the same reviewer; once a second implementer joins, each module also requires the other one.",
        "",
    ]
    for module, owner, paths in modules:
        owner = owner.strip()
        if owner == "any":
            continue
        extra = [gh[h] for h in sorted(implementers) if h != owner and owner != "joint"]
        who = " ".join(dict.fromkeys(base.split() + extra))
        note = f"# {module} — implemented by {owner}"
        for path in (p.strip().strip('"') for p in paths.split(",")):
            entry = "/" + path.replace("/**", "/").lstrip("/")
            lines.append(f"{entry:<35} {who:<20} {note}")

    text = "\n".join(lines) + "\n"
    if "--check" in sys.argv:
        if OUT.read_text() != text:
            print("::error::CODEOWNERS is out of date — run scripts/gen_codeowners.py and commit the result")
            return 1
        print("CODEOWNERS OK")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
